FROM ubuntu:latest

# Copy wordlists
COPY wordlists /wordlists

# Copy relevant Markdown files
COPY NOTICE.md /wordlists/NOTICE.md
COPY TERMS_OF_USE.md /wordlists/TERMS_OF_USE.md

# Unzip rockyou
WORKDIR /wordlists/famous
RUN apt-get update && apt-get install -y unzip && \
  unzip rockyou.zip && rm rockyou.zip

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*