name: Labeler

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6
        with:
          configuration-path: .github/labeler.yml
