name: Labeler

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
        with:
          configuration-path: .github/labeler.yml
